services:
    contao.install_tool:
        class: Contao\InstallationBundle\InstallTool
        public: false
        arguments:
            - "%doctrine.default_connection%"
            - "%kernel.root_dir%"

    contao.install_tool_user:
        class: Contao\InstallationBundle\InstallToolUser
        public: false
        arguments:
            - "%kernel.root_dir%"

    contao.installer:
        class: Contao\InstallationBundle\Database\Installer
        public: false
        arguments:
            - "%doctrine.default_connection%"
            - "@contao.resource_finder"
            - "%translator.class%"
